// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALM3jRSPjy9ubhMAzfIF3lS9SVz4pDJt4',
    appId: '1:800722829612:web:3d69c13fcc65d7f88f6c89',
    messagingSenderId: '800722829612',
    projectId: 'portal-grobogan',
    authDomain: 'portal-grobogan.firebaseapp.com',
    storageBucket: 'portal-grobogan.firebasestorage.app',
    measurementId: 'G-BQXT4QV60N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8B3bVzwlju5n13GQVxVxk6TZXJWKxH5Y',
    appId: '1:800722829612:android:6bff19f66b934a648f6c89',
    messagingSenderId: '800722829612',
    projectId: 'portal-grobogan',
    storageBucket: 'portal-grobogan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChiBztB_Ja_-aZmbxasNKplE-2nbJIoPQ',
    appId: '1:800722829612:ios:b7797a28e053dd7c8f6c89',
    messagingSenderId: '800722829612',
    projectId: 'portal-grobogan',
    storageBucket: 'portal-grobogan.firebasestorage.app',
    iosBundleId: 'id.grobogan.portalGrobogan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChiBztB_Ja_-aZmbxasNKplE-2nbJIoPQ',
    appId: '1:800722829612:ios:b7797a28e053dd7c8f6c89',
    messagingSenderId: '800722829612',
    projectId: 'portal-grobogan',
    storageBucket: 'portal-grobogan.firebasestorage.app',
    iosBundleId: 'id.grobogan.portalGrobogan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALM3jRSPjy9ubhMAzfIF3lS9SVz4pDJt4',
    appId: '1:800722829612:web:8102b775d4144d378f6c89',
    messagingSenderId: '800722829612',
    projectId: 'portal-grobogan',
    authDomain: 'portal-grobogan.firebaseapp.com',
    storageBucket: 'portal-grobogan.firebasestorage.app',
    measurementId: 'G-NB7YVFSK4S',
  );
}
